### ISSUE TITLE
Scripts that are prefixed with network should overwrite when generating client

### ISSUE THREAD

**Issue by benbackend** [bjartek/overflow#102]
**Is your feature request related to a problem? Please describe.**
Scripts that are prefixed with network should overwrite the other script with the same name in generating client

```
e.g. 
./scripts
   ├──getInfo.cdc 
   └──mainnetgetInfo.cdc
```
   
   The client should take mainnetgetInfo for mainnet and getInfo for testnet and emulator

**Comment by bjartek** [comment]
Agreed
