### ISSUE TITLE
flags with args on make

### ISSUE THREAD

**Issue by 0xmovses** [bjartek/overflow#18]
It would be really super cool if I could pass in args with flags when I run a make file. The values for these args would be some account in flow.json for example. 

``make setup-fusd-account --account artist-one --network testnet``
 
Perhaps there is already a native Golang way to do this? At the moment I'm manually updating the tasks to run certain tx's on our contracts on testnet. Also notice in the example above, I added the flag for --network, similar to the flow CLI. This would be cool as right now I have duplicates of tasks, some that run that use the testnet method, some that run in emulator. It would be nice to avoid this. 

Really enjoying the power of overflow!

**Comment by bjartek** [comment]
The easiest way is to use env vars. account=foo and read env var for that.

If you use NewOverflow builder it support OVERFLOW_ENV already so your goal could just use that
