### ISSUE TITLE
How to pass in Arg of type Address to transaction without Key

### ISSUE THREAD

**Issue by 0xmovses** [bjartek/overflow#20]
In the instance that I'm running a transaction on Testnet of Mainnet. My Admin account is the Signer of this Tx, but this Tx, required a parameter of type Address. Previously in testing I would do 

```
flow.TransactionFromFile("register_token").SignProposeAndPayAs("admin").Args(flow.Arguments().Account("artist-test")).RunPrintEventsFull()
```
And the transaction would execute. However, in testnet, if I try to run ``.Account()`` I need the key of that account in my flow.json. 

How can I pass in an argument of type address when it is not my account? I think you pointed to something on this yesterday.

**Comment by bjartek** [comment]
Added an alias RawAddress/Address to RawAccount/Account in 268c6dc
