### ISSUE TITLE
Bootstrap a new project

### ISSUE THREAD

**Issue by bjartek** [bjartek/overflow#28]
When creating a new project today one of the major hurdles is populating a flow.json properly. 

Having the ability to specify somethings in flow.json and then have overflow/flowkit just fix the remaining things would be great
 - creating new accounts on testnet
 - funding accounts
 - downloading contracts and specifying correct addresses

**Comment by hichana** [comment]
This would indeed be very helpful

**Comment by bjartek** [comment]
Create a github-template overflow project

    github actions
    gomplate for replacing values in files
    cli command to start the process and kick off editing the config file

Features:

    Create basic NFT with your custom name
    Seperate Admin contract
    Tests in overflow
    cadence-docs
    format the code? (is there prettier yet?)

**Comment by bjartek** [comment]
this can be done with flow scaffold
