### ISSUE TITLE
Can't auto-deploy contracts to multiple accounts

### ISSUE THREAD

**Issue by justjoolz** [bjartek/overflow#29]
When parsing the Flow.json deployments section, if the secondary emulator accounts are not created in advance overflow will produce the following error:

```
2022/04/28 10:01:12 failed to fetch information for account 01cf0e2f2f715450 with error failed to get account with address 01cf0e2f2f715450: client: rpc error: code = NotFound desc = could not find account with address 01cf0e2f2f715450
```

```
Works:

 "deployments": {
    "emulator": {
      "emulator-account": [
        "NonFungibleToken",
        "MetadataViews",
        "ExampleNFT",
        "BYC"
      ],
      "emulator-admin-account": [
    
      ],
 
Doesn't Work:

 "deployments": {
    "emulator": {
      "emulator-account": [
        "NonFungibleToken",
        "MetadataViews"
      ],
      "emulator-admin-account": [
       "ExampleNFT",
        "BYC"
      ],
 
```

**Comment by bjartek** [comment]
I do not think it supports deploying contracts in multiple accounts on emulator.

If you want this create an issue.

**Comment by justjoolz** [comment]
I usually only deploy the missing standard contracts to the emulator account and have an admin account for all the projects contracts

I just assumed that overflow functioned in same way as the cli project deploy command...
