### ISSUE TITLE
Contract deployment error when using secure Cadence syntax

### ISSUE THREAD

**Issue by hichana** [bjartek/overflow#31]
I've upgraded to Flow version v0.33.1-sc-m5. When using secure Cadence syntax and the manually-run emulator, my NFT contract deploys fine. When using the embedded emulator it does not and I get this error:

```
return (&self.ownedNFTs[id] as &NonFungibleToken.NFT?)!
                                                       ^^^^^^^^^^^^^^^^^^^^^^ expected reference type, got `&NonFungibleToken.NFT?`

error: cannot create reference
```

Is the embedded emulator somehow not using the same emulator version as the manually-run emulator?

**Comment by bjartek** [comment]
Have you tried with the secure-cadence branch of overflow?

The emulator you run in flow-cli does not have to be the same version as the one in overflow.

**Comment by hichana** [comment]
Nope, I didn't know it exists but realize I should have looked for something like that. How does one actually use a different branch after installing via `go get github.com/bjartek/overflow/overflow`?

**Comment by bjartek** [comment]
You go get a different commit or branch.

**Comment by hichana** [comment]
Alright, removing my previous overflow install (`go.mod` and `go.sum`) and re-installing except with the `go get` part as follows now allows me to run embedded emulator with secure-cadence syntax:

```
go get github.com/bjartek/overflow/overflow@secure-cadence
```

Thanks @bjartek
