### ISSUE TITLE
Possibility of using overflow in `lib/go/` of contract directories

### ISSUE THREAD

**Issue by joshuahannan** [bjartek/overflow#9]
I am strongly considering updating the flow contracts repositories to use `flow.json` and overflow, but I don't know if overflow is compatible with the way I have my repos organized. I currently have a `lib/` directory that is meant to contain language specific packages and libraries, and I like to keep anything language specific in those and have the top level directory be generic. 

It seems like overflow needs to be imported in the top level directory with the flow.json file? Would it be possible to import it in my [`lib/go/test/` package](https://github.com/onflow/flow-core-contracts/tree/master/lib/go/test) and use it from there? I haven't spent a much time looking into overflow yet, so I'm not that familiar with how it works. The tests that use it are much cleaner than mine though. 😉

**Comment by bjartek** [comment]
Good timing! These are one of the issues I want to tackle! I will do this tomorrow i think! The plan for the example folder is to be as close to the recommended cadence structure as possible so. 

cadence/contracts/
cadence/scripts/
cadence/transactions
lib/go/test/
flow.json

Is this the recommended structure?

**Comment by joshuahannan** [comment]
Most of mine have `contracts/`, `scripts/`, and `transactions/` in the root of the repo instead of in a `cadence/` folder, but I could understand wanting to put them in a `cadence/` folder if you have front end stuff in the repo also. I think as long as it supports both, that should be fine.

**Comment by bjartek** [comment]
It should not be a problem supporting both.

**Comment by bjartek** [comment]
I have dug a little more and the `Deploy` command on Project does not allow specifying a relative path so you really need a seperate flow json for each path you want to run that command from.

**Comment by bjartek** [comment]
I merged the pr to have it in mainline but i will leave this issue open since I think it should be fixed in a better way.
